name: CICD Pipeline Dev To Production

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CICD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1
        with:
<<<<<<< HEAD
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
=======
          host: "20.49.49.79"
          username: "Agile"
          password: "Agilpermana72"
>>>>>>> 63d5b40fd03b0db49a484fa4e111f77da7425a01
          # Uncomment if your SSH port is different
          # port: 22
          script: |
            echo "Deploying to production server..."

# TEst RunAdbidgida dhuiahda
