name: CICD Pipeline Dev To Production

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CICD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # Uncomment if your SSH port is different
          # port: 22
          script: |
            echo "Deploying to production server..."

            cd /home/Agile
            echo "Berhasil masuk ke folder Agile"

            sudo docker compose up -d #menjalankan docker compose di server
            echo "Berhasil menjalankan docker compose di server"

# TEst RunAdbidgida dhuiahda
